// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Odmon.Worker.Data;

#nullable disable

namespace Odmon.Worker.Migrations
{
    [DbContext(typeof(IntegrationDbContext))]
    [Migration("20251109143557_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Odmon.Worker.Models.MondayItemMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("LastSyncFromMondayUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastSyncFromOdcanitUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("MondayChecksum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("MondayItemId")
                        .HasColumnType("bigint");

                    b.Property<string>("OdcanitVersion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TikCounter")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MondayItemId");

                    b.HasIndex("TikCounter");

                    b.ToTable("MondayItemMappings");
                });

            modelBuilder.Entity("Odmon.Worker.Models.SyncLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SyncLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
