// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Odmon.Worker.Data;

#nullable disable

namespace Odmon.Worker.Migrations
{
    [DbContext(typeof(IntegrationDbContext))]
    [Migration("20260203000000_AddMondayItemMappingIndexes")]
    partial class AddMondayItemMappingIndexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Odmon.Worker.Models.AllowedTik", b =>
                {
                    b.Property<int>("TikCounter")
                        .HasColumnType("int");

                    b.HasKey("TikCounter");

                    b.ToTable("AllowedTik", (string)null);
                });

            modelBuilder.Entity("Odmon.Worker.Models.HearingNearestSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("BoardId")
                        .HasColumnType("bigint");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JudgeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastSyncedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("MondayItemId")
                        .HasColumnType("bigint");

                    b.Property<int?>("NearestMeetStatus")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NearestStartDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("TikCounter")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MondayItemId");

                    b.HasIndex("TikCounter", "BoardId")
                        .IsUnique();

                    b.ToTable("HearingNearestSnapshots", (string)null);
                });

            modelBuilder.Entity("Odmon.Worker.Models.MondayHearingApprovalState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("BoardId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("LastSyncedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("MondayItemId")
                        .HasColumnType("bigint");

                    b.Property<string>("StatusIndex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TikCounter")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BoardId", "MondayItemId")
                        .IsUnique();

                    b.ToTable("MondayHearingApprovalStates", (string)null);
                });

            modelBuilder.Entity("Odmon.Worker.Models.MondayItemMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("BoardId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsTest")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastSyncFromMondayUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastSyncFromOdcanitUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("MondayChecksum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("MondayItemId")
                        .HasColumnType("bigint");

                    b.Property<string>("OdcanitVersion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TikCounter")
                        .HasColumnType("int");

                    b.Property<string>("TikNumber")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("MondayItemId");

                    b.HasIndex("TikCounter")
                        .IsUnique();

                    b.HasIndex("TikNumber", "BoardId");

                    b.ToTable("MondayItemMappings", (string)null);
                });

            modelBuilder.Entity("Odmon.Worker.Models.NispahAuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CorrelationId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErrorOutput")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Info")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NispahTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Outcome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TikVisualID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("TikVisualID", "CreatedAtUtc");

                    b.ToTable("NispahAuditLogs", (string)null);
                });

            modelBuilder.Entity("Odmon.Worker.Models.NispahDeduplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("InfoHash")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NispahTypeName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TikVisualID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("TikVisualID", "NispahTypeName", "InfoHash")
                        .IsUnique()
                        .HasFilter("[TikVisualID] IS NOT NULL AND [NispahTypeName] IS NOT NULL AND [InfoHash] IS NOT NULL");

                    b.ToTable("NispahDeduplications", (string)null);
                });

            modelBuilder.Entity("Odmon.Worker.Models.SyncLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Level")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SyncLogs", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
