// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Odmon.Worker.Data;

#nullable disable

namespace Odmon.Worker.Migrations
{
    [DbContext(typeof(IntegrationDbContext))]
    [Migration("20260830154754_AddEmailFilingResolutionPhantom")]
    partial class AddEmailFilingResolutionPhantom
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Odmon.Worker.Models.AllowedTik", b =>
                {
                    b.Property<int>("TikCounter")
                        .HasColumnType("int");

                    b.HasKey("TikCounter");

                    b.ToTable("AllowedTik", (string)null);
                });

            modelBuilder.Entity("Odmon.Worker.Models.CaseAnnexWriteState", b =>
                {
                    b.Property<int>("TikCounter")
                        .HasColumnType("int");

                    b.Property<bool>("AccidentStoryAnnexWritten")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("AccidentStoryAnnexWrittenAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("AccidentStoryAnnexWrittenRunId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("TikCounter");

                    b.ToTable("CaseAnnexWriteState", (string)null);
                });

            modelBuilder.Entity("Odmon.Worker.Models.EmailAlertDedup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ExceptionType")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("FirstSeenUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastEmailSentUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastSeenUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("OccurrenceCount")
                        .HasColumnType("int");

                    b.Property<string>("Source")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Subject")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int>("SuppressedCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Fingerprint")
                        .IsUnique();

                    b.HasIndex("LastSeenUtc");

                    b.ToTable("EmailAlertDedups", (string)null);
                });

            modelBuilder.Entity("Odmon.Worker.Models.EmailAutomationLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ActualForwardTo")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DetectedCourtCaseNumber")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("GraphMessageId")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("InternetMessageId")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Mailbox")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<DateTime?>("ProcessedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ReceivedDateTimeUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ResolvedClientNumber")
                        .HasColumnType("int");

                    b.Property<string>("ResolvedTargetEmail")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<int?>("ResolvedTikCounter")
                        .HasColumnType("int");

                    b.Property<string>("ResolvedTikNumber")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("RuleName")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Sender")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("Subject")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("TargetEmail")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasFilter("[IdempotencyKey] IS NOT NULL");

                    b.HasIndex("Mailbox", "GraphMessageId");

                    b.ToTable("EmailAutomationLogs", (string)null);
                });

            modelBuilder.Entity("Odmon.Worker.Models.EmailAutomationMailboxState", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeltaLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FolderId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("LastSuccessfulSyncUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Mailbox")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<DateTime>("ProcessingFromUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Mailbox", "FolderId")
                        .IsUnique();

                    b.ToTable("EmailAutomationMailboxStates", (string)null);
                });

            modelBuilder.Entity("Odmon.Worker.Models.EmailFilingCandidateDiagnostic", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Candidate")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("CandidateType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<long>("EmailFilingDiagnosticId")
                        .HasColumnType("bigint");

                    b.Property<string>("ResolutionStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int?>("ResolvedTikCounter")
                        .HasColumnType("int");

                    b.Property<string>("ResolvedTikNumber")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("Id");

                    b.HasIndex("EmailFilingDiagnosticId");

                    b.HasIndex("CandidateType", "ResolutionStatus");

                    b.ToTable("EmailFilingCandidateDiagnostics", (string)null);
                });

            modelBuilder.Entity("Odmon.Worker.Models.EmailFilingDedup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("ExpectedFileLength")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("FiledAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastErrorCategory")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("MessageFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int?>("OdcanitDocCounter")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("TikCounter")
                        .HasColumnType("int");

                    b.Property<string>("TikNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MessageFingerprint", "TikCounter")
                        .IsUnique();

                    b.ToTable("EmailFilingDedups", (string)null);
                });

            modelBuilder.Entity("Odmon.Worker.Models.EmailFilingDiagnostic", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("CourtCandidateCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("DedupHitCount")
                        .HasColumnType("int");

                    b.Property<string>("FinalDecision")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Mailbox")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("MessageFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ObserverClassifications")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("ReceivedDateTimeUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("ResolvedCourtCount")
                        .HasColumnType("int");

                    b.Property<int>("ResolvedTikCount")
                        .HasColumnType("int");

                    b.Property<int>("SuspectNotCaseCount")
                        .HasColumnType("int");

                    b.Property<int>("TargetCount")
                        .HasColumnType("int");

                    b.Property<int>("TikCandidateCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("FinalDecision");

                    b.HasIndex("MessageFingerprint");

                    b.ToTable("EmailFilingDiagnostics", (string)null);
                });

            modelBuilder.Entity("Odmon.Worker.Models.EmailFilingMailboxState", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeltaLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FolderId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("LastSuccessfulSyncUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Mailbox")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<DateTime>("ProcessingFromUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Mailbox", "FolderId")
                        .IsUnique();

                    b.ToTable("EmailFilingMailboxStates", (string)null);
                });

            modelBuilder.Entity("Odmon.Worker.Models.EmailFilingResolutionRun", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AgreementWithExistingAuthority")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("nvarchar(48)");

                    b.Property<int>("ClaimCandidateCounterCount")
                        .HasColumnType("int");

                    b.Property<int>("ClaimPrimaryValueCount")
                        .HasColumnType("int");

                    b.Property<int>("CourtCandidateCounterCount")
                        .HasColumnType("int");

                    b.Property<int>("CourtPrimaryValueCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("EmailFilingDiagnosticId")
                        .HasColumnType("bigint");

                    b.Property<int>("ExistingAuthorityTargetCount")
                        .HasColumnType("int");

                    b.Property<long>("ExtractionDurationMs")
                        .HasColumnType("bigint");

                    b.Property<string>("FinalResolutionClass")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("nvarchar(48)");

                    b.Property<bool>("NarrowingApplied")
                        .HasColumnType("bit");

                    b.Property<string>("ObserverErrorCategory")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("PhantomTargetCount")
                        .HasColumnType("int");

                    b.Property<int>("PrimaryEvidenceTypeMask")
                        .HasColumnType("int");

                    b.Property<long>("PrimaryResolutionDurationMs")
                        .HasColumnType("bigint");

                    b.Property<int>("SupportingEvidenceTypeMask")
                        .HasColumnType("int");

                    b.Property<long>("SupportingNarrowingDurationMs")
                        .HasColumnType("bigint");

                    b.Property<int>("TikCandidateCounterCount")
                        .HasColumnType("int");

                    b.Property<int>("TikPrimaryValueCount")
                        .HasColumnType("int");

                    b.Property<long>("TotalPhantomDurationMs")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AgreementWithExistingAuthority");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("EmailFilingDiagnosticId")
                        .IsUnique();

                    b.HasIndex("FinalResolutionClass");

                    b.ToTable("EmailFilingResolutionRuns", (string)null);
                });

            modelBuilder.Entity("Odmon.Worker.Models.EmailFilingResolutionTarget", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ResolutionRunId")
                        .HasColumnType("bigint");

                    b.Property<string>("TargetKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("TikCounter")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TargetKind", "TikCounter");

                    b.HasIndex("ResolutionRunId", "TikCounter", "TargetKind")
                        .IsUnique();

                    b.ToTable("EmailFilingResolutionTargets", (string)null);
                });

            modelBuilder.Entity("Odmon.Worker.Models.EmailFilingTargetDiagnostic", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("DedupResult")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<long>("EmailFilingDiagnosticId")
                        .HasColumnType("bigint");

                    b.Property<bool>("RealWriteAllowlisted")
                        .HasColumnType("bit");

                    b.Property<int>("TikCounter")
                        .HasColumnType("int");

                    b.Property<string>("TikNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("Decision");

                    b.HasIndex("EmailFilingDiagnosticId");

                    b.HasIndex("TikCounter");

                    b.ToTable("EmailFilingTargetDiagnostics", (string)null);
                });

            modelBuilder.Entity("Odmon.Worker.Models.HearingBackfillApr2026", b =>
                {
                    b.Property<string>("ClientNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("מספר לקוח");

                    b.Property<string>("CourtCity")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("עיר בית משפט");

                    b.Property<string>("DriverName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("שם נהג");

                    b.Property<string>("DriverPhone")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("טלפון נהג");

                    b.Property<DateTime?>("EventDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("תאריך אירוע");

                    b.Property<DateTime?>("HearingDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("תאריך דיון");

                    b.Property<string>("HearingTime")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("שעת דיון");

                    b.Property<string>("JudgeName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("שם שופט");

                    b.Property<string>("TikNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("מספר תיק");

                    b.ToTable("HearingBackfill_Apr2026", (string)null);
                });

            modelBuilder.Entity("Odmon.Worker.Models.HearingNearestSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("BoardId")
                        .HasColumnType("bigint");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JudgeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastSyncedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("MondayItemId")
                        .HasColumnType("bigint");

                    b.Property<int?>("NearestMeetStatus")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NearestStartDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("TikCounter")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MondayItemId");

                    b.HasIndex("TikCounter", "BoardId")
                        .IsUnique();

                    b.ToTable("HearingNearestSnapshots", (string)null);
                });

            modelBuilder.Entity("Odmon.Worker.Models.ListenerState", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastChangeFeedWatermarkUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ListenerState", (string)null);
                });

            modelBuilder.Entity("Odmon.Worker.Models.MondayDocumentImport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AlertSent")
                        .HasColumnType("bit");

                    b.Property<string>("AssetId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ColumnId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("InboxFilePath")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<DateTime?>("LastAttemptAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<long?>("LinkedCaseItemId")
                        .HasColumnType("bigint");

                    b.Property<long>("MondayQuestionnaireItemId")
                        .HasColumnType("bigint");

                    b.Property<string>("OdcanitDestPath")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<int?>("OdcanitDocCounter")
                        .HasColumnType("int");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("TikCounter")
                        .HasColumnType("int");

                    b.Property<string>("TikVisualID")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("TikCounter");

                    b.HasIndex("MondayQuestionnaireItemId", "ColumnId", "AssetId")
                        .IsUnique();

                    b.ToTable("MondayDocumentImports", (string)null);
                });

            modelBuilder.Entity("Odmon.Worker.Models.MondayHearingApprovalState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("BoardId")
                        .HasColumnType("bigint");

                    b.Property<string>("FirstDecision")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastKnownStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastWriteAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("MondayItemId")
                        .HasColumnType("bigint");

                    b.Property<int>("TikCounter")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BoardId", "MondayItemId")
                        .IsUnique();

                    b.ToTable("MondayHearingApprovalStates", (string)null);
                });

            modelBuilder.Entity("Odmon.Worker.Models.MondayItemMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("BoardId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("HearingChecksum")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("IsTest")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastSyncFromMondayUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastSyncFromOdcanitUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("MondayChecksum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("MondayItemId")
                        .HasColumnType("bigint");

                    b.Property<string>("OdcanitVersion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TikCounter")
                        .HasColumnType("int");

                    b.Property<string>("TikNumber")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("MondayItemId");

                    b.HasIndex("TikCounter")
                        .IsUnique();

                    b.HasIndex("TikNumber", "BoardId");

                    b.ToTable("MondayItemMappings", t =>
                        {
                            t.HasCheckConstraint("CK_MondayItemMappings_TikCounter_Positive", "[TikCounter] > 0");
                        });
                });

            modelBuilder.Entity("Odmon.Worker.Models.NetCourtDecisionAlert", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ActualRecipientEmail")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("AlertQueuedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ClientNumber")
                        .HasColumnType("int");

                    b.Property<long?>("CourtDocumentID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DecisionDesc")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<long?>("DecisionID")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("DocDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DocType")
                        .HasColumnType("int");

                    b.Property<string>("DocumentIdentity")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("EmailMode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("IntendedRecipientEmail")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<long>("NetCourtCounter")
                        .HasColumnType("bigint");

                    b.Property<long?>("ODDocID")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("TikCounter")
                        .HasColumnType("int");

                    b.Property<string>("TikNumber")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime?>("tsCreateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("DocumentIdentity")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("NetCourtDecisionAlerts", (string)null);
                });

            modelBuilder.Entity("Odmon.Worker.Models.NetCourtDecisionAlertState", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("BaselineCompletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<long?>("LastSeenCounter")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("NetCourtDecisionAlertState", (string)null);
                });

            modelBuilder.Entity("Odmon.Worker.Models.NispahAuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InfoHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InfoLength")
                        .HasColumnType("int");

                    b.Property<string>("NispahTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TikVisualID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("TikVisualID", "CreatedAtUtc");

                    b.ToTable("NispahAuditLogs", (string)null);
                });

            modelBuilder.Entity("Odmon.Worker.Models.NispahDeduplication", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("InfoHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NispahTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TikVisualID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("TikVisualID", "NispahTypeName", "InfoHash")
                        .IsUnique();

                    b.ToTable("NispahDeduplications", (string)null);
                });

            modelBuilder.Entity("Odmon.Worker.Models.NispahWriteLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("Failed")
                        .HasColumnType("bit");

                    b.Property<string>("InfoHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("NispahType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<long?>("SourceAssetId")
                        .HasColumnType("bigint");

                    b.Property<long>("SourceItemId")
                        .HasColumnType("bigint");

                    b.Property<string>("SourceKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("TikCounter")
                        .HasColumnType("int");

                    b.Property<string>("TikVisualId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("TikCounter", "NispahType", "SourceItemId", "InfoHash")
                        .IsUnique();

                    b.ToTable("NispahWriteLogs", (string)null);
                });

            modelBuilder.Entity("Odmon.Worker.Models.OdcanitCase", b =>
                {
                    b.Property<string>("Additional")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientVisualID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EventDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("HalichName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("HozlapBalanceCalcDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("HozlapOpenDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("HozlapTikNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LishkaName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MautName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Referant")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("RequestedClaimAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SideCounter")
                        .HasColumnType("int");

                    b.Property<int?>("StageCode")
                        .HasColumnType("int");

                    b.Property<string>("StageName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StatusChangedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeamName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TikBalanceCalcDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TikCloseDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TikCounter")
                        .HasColumnType("int");

                    b.Property<string>("TikName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TikNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TikOwner")
                        .HasColumnType("int");

                    b.Property<string>("TikType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TiukDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TiukName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("tsCreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("tsModifyDate")
                        .HasColumnType("datetime2");

                    b.ToTable((string)null);

                    b.ToView(null, (string)null);
                });

            modelBuilder.Entity("Odmon.Worker.Models.SyncFailure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("BoardId")
                        .HasColumnType("bigint");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ErrorType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("Resolved")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ResolvedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("RetryAttempts")
                        .HasColumnType("int");

                    b.Property<string>("RunId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("StackTrace")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("TikCounter")
                        .HasColumnType("int");

                    b.Property<string>("TikNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Resolved");

                    b.HasIndex("RunId");

                    b.HasIndex("TikCounter", "OccurredAtUtc");

                    b.ToTable("SyncFailures", (string)null);
                });

            modelBuilder.Entity("Odmon.Worker.Models.SyncLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SyncLogs");
                });

            modelBuilder.Entity("Odmon.Worker.Models.SyncRunLock", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LockedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("LockedByRunId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.ToTable("SyncRunLocks", (string)null);
                });

            modelBuilder.Entity("Odmon.Worker.Models.SyncRunMetric", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BootstrapCreated")
                        .HasColumnType("int");

                    b.Property<int>("BootstrapFailed")
                        .HasColumnType("int");

                    b.Property<bool>("CircuitBreakerTripped")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("CoolingFilteredOut")
                        .HasColumnType("int");

                    b.Property<string>("DataSource")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("DurationMs")
                        .HasColumnType("int");

                    b.Property<int>("Failed")
                        .HasColumnType("int");

                    b.Property<string>("RunId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("SkippedDuplicate")
                        .HasColumnType("int");

                    b.Property<int>("SkippedInactive")
                        .HasColumnType("int");

                    b.Property<int>("SkippedNoChange")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Updated")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RunId")
                        .IsUnique();

                    b.HasIndex("StartedAtUtc");

                    b.ToTable("SyncRunMetrics", (string)null);
                });

            modelBuilder.Entity("Odmon.Worker.Models.VoicenterApiRequestLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CallId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("EndpointType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int?>("HttpStatus")
                        .HasColumnType("int");

                    b.Property<bool>("QuotaExceeded")
                        .HasColumnType("bit");

                    b.Property<bool>("Success")
                        .HasColumnType("bit");

                    b.Property<DateTime>("WeekStartUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CallId")
                        .HasDatabaseName("IX_VoicenterApiRequestLogs_CallId");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("IX_VoicenterApiRequestLogs_CreatedAtUtc");

                    b.HasIndex("WeekStartUtc")
                        .HasDatabaseName("IX_VoicenterApiRequestLogs_WeekStartUtc");

                    b.HasIndex("EndpointType", "WeekStartUtc")
                        .HasDatabaseName("IX_VoicenterApiRequestLogs_EndpointType_WeekStartUtc");

                    b.ToTable("VoicenterApiRequestLogs", (string)null);
                });

            modelBuilder.Entity("Odmon.Worker.Models.VoicenterCallProcessingState", b =>
                {
                    b.Property<string>("CallId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("Attempts")
                        .HasColumnType("int");

                    b.Property<DateTime>("FirstSeenUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastCheckedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("LastSeenUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int?>("TikCounter")
                        .HasColumnType("int");

                    b.Property<string>("TikVisualId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("CallId");

                    b.HasIndex("LastSeenUtc")
                        .HasDatabaseName("IX_VoicenterCallProcessingStates_LastSeenUtc");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_VoicenterCallProcessingStates_Status");

                    b.ToTable("VoicenterCallProcessingStates", (string)null);
                });

            modelBuilder.Entity("Odmon.Worker.Models.VoicenterQuotaWarningState", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("EndpointType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("HardLimit")
                        .HasColumnType("int");

                    b.Property<int>("RequestCountAtWarning")
                        .HasColumnType("int");

                    b.Property<int>("Threshold")
                        .HasColumnType("int");

                    b.Property<DateTime>("WarningSentAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("WeekStartUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("WeekStartUtc", "EndpointType")
                        .IsUnique()
                        .HasDatabaseName("UX_VoicenterQuotaWarningStates_Week_Endpoint");

                    b.ToTable("VoicenterQuotaWarningStates", (string)null);
                });

            modelBuilder.Entity("Odmon.Worker.Models.EmailFilingCandidateDiagnostic", b =>
                {
                    b.HasOne("Odmon.Worker.Models.EmailFilingDiagnostic", "EmailFilingDiagnostic")
                        .WithMany("Candidates")
                        .HasForeignKey("EmailFilingDiagnosticId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmailFilingDiagnostic");
                });

            modelBuilder.Entity("Odmon.Worker.Models.EmailFilingResolutionRun", b =>
                {
                    b.HasOne("Odmon.Worker.Models.EmailFilingDiagnostic", "EmailFilingDiagnostic")
                        .WithOne("ResolutionRun")
                        .HasForeignKey("Odmon.Worker.Models.EmailFilingResolutionRun", "EmailFilingDiagnosticId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmailFilingDiagnostic");
                });

            modelBuilder.Entity("Odmon.Worker.Models.EmailFilingResolutionTarget", b =>
                {
                    b.HasOne("Odmon.Worker.Models.EmailFilingResolutionRun", "ResolutionRun")
                        .WithMany("Targets")
                        .HasForeignKey("ResolutionRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ResolutionRun");
                });

            modelBuilder.Entity("Odmon.Worker.Models.EmailFilingTargetDiagnostic", b =>
                {
                    b.HasOne("Odmon.Worker.Models.EmailFilingDiagnostic", "EmailFilingDiagnostic")
                        .WithMany("Targets")
                        .HasForeignKey("EmailFilingDiagnosticId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmailFilingDiagnostic");
                });

            modelBuilder.Entity("Odmon.Worker.Models.EmailFilingDiagnostic", b =>
                {
                    b.Navigation("Candidates");

                    b.Navigation("ResolutionRun");

                    b.Navigation("Targets");
                });

            modelBuilder.Entity("Odmon.Worker.Models.EmailFilingResolutionRun", b =>
                {
                    b.Navigation("Targets");
                });
#pragma warning restore 612, 618
        }
    }
}
