// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Odmon.Worker.Data;

#nullable disable

namespace Odmon.Worker.Migrations
{
    [DbContext(typeof(IntegrationDbContext))]
    [Migration("20260202085642_AddHearingNearestSnapshot_Only")]
    partial class AddHearingNearestSnapshot_Only
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Odmon.Worker.Models.AllowedTik", b =>
                {
                    b.Property<int>("TikCounter")
                        .HasColumnType("int");

                    b.HasKey("TikCounter");

                    b.ToTable("AllowedTik", (string)null);
                });

            modelBuilder.Entity("Odmon.Worker.Models.HearingNearestSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("BoardId")
                        .HasColumnType("bigint");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JudgeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastSyncedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("MondayItemId")
                        .HasColumnType("bigint");

                    b.Property<int?>("NearestMeetStatus")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NearestStartDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("TikCounter")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MondayItemId");

                    b.HasIndex("TikCounter", "BoardId")
                        .IsUnique();

                    b.ToTable("HearingNearestSnapshots", (string)null);
                });

            modelBuilder.Entity("Odmon.Worker.Models.MondayHearingApprovalState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("BoardId")
                        .HasColumnType("bigint");

                    b.Property<string>("FirstDecision")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastKnownStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastWriteAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("MondayItemId")
                        .HasColumnType("bigint");

                    b.Property<int>("TikCounter")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BoardId", "MondayItemId")
                        .IsUnique();

                    b.ToTable("MondayHearingApprovalStates", (string)null);
                });

            modelBuilder.Entity("Odmon.Worker.Models.MondayItemMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("BoardId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsTest")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastSyncFromMondayUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastSyncFromOdcanitUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("MondayChecksum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("MondayItemId")
                        .HasColumnType("bigint");

                    b.Property<string>("OdcanitVersion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TikCounter")
                        .HasColumnType("int");

                    b.Property<string>("TikNumber")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("MondayItemId");

                    b.HasIndex("TikCounter")
                        .IsUnique();

                    b.HasIndex("TikNumber", "BoardId");

                    b.ToTable("MondayItemMappings");
                });

            modelBuilder.Entity("Odmon.Worker.Models.NispahAuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InfoHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InfoLength")
                        .HasColumnType("int");

                    b.Property<string>("NispahTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TikVisualID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("TikVisualID", "CreatedAtUtc");

                    b.ToTable("NispahAuditLogs", (string)null);
                });

            modelBuilder.Entity("Odmon.Worker.Models.NispahDeduplication", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("InfoHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NispahTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TikVisualID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("TikVisualID", "NispahTypeName", "InfoHash")
                        .IsUnique();

                    b.ToTable("NispahDeduplications", (string)null);
                });

            modelBuilder.Entity("Odmon.Worker.Models.OdcanitCase", b =>
                {
                    b.Property<string>("Additional")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientVisualID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EventDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("HalichName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("HozlapBalanceCalcDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("HozlapOpenDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("HozlapTikNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LishkaName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MautName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Referant")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("RequestedClaimAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SideCounter")
                        .HasColumnType("int");

                    b.Property<int?>("StageCode")
                        .HasColumnType("int");

                    b.Property<string>("StageName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StatusChangedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeamName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TikBalanceCalcDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TikCloseDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TikCounter")
                        .HasColumnType("int");

                    b.Property<string>("TikName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TikNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TikOwner")
                        .HasColumnType("int");

                    b.Property<string>("TikType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TiukDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TiukName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("tsCreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("tsModifyDate")
                        .HasColumnType("datetime2");

                    b.ToTable((string)null);

                    b.ToView(null, (string)null);
                });

            modelBuilder.Entity("Odmon.Worker.Models.SyncLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SyncLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
